# -*- coding: utf-8 -*-
"""duplicate_values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KYYn-7-gPe8UqGFeBGpNp0tyGBSBaZH
"""

import pandas as pd

df=pd.read_csv("winequality-red.csv")
#null values are replaced by mean
df=df.fillna(df.mean())

#identify the duplicatae values
duplicates=df.duplicated().sum()
print(f"Total number of duplicated rows : ",duplicates)

#handle duplicate values

#it is remove the last occurance of the duplicated row
clean_df=df.drop_duplicates(keep='first')

duplicates=clean_df.duplicated().sum()
print(f"Total number of duplicated rows : ",duplicates)
print(clean_df.shape)

# it is remove the both occurance
clean_df1=df.drop_duplicates(keep=False)

duplicates=clean_df1.duplicated().sum()
print(f"Total number of duplicated rows : ",duplicates)
print(clean_df1.shape)

#it is remove the fist occurance of duplicated row
clean_df2=df.drop_duplicates(keep='last')

duplicates=clean_df2.duplicated().sum()
print(f"Total number of duplicated rows : ",duplicates)
print(clean_df2.shape)

