# -*- coding: utf-8 -*-
"""data_science1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10c9i5ZBfP_kjeNMQk_ODPrFQduV9SSI1
"""

import pandas as pd

#load the dataset
df=pd.read_csv("winequality-red.csv")

#identify the null values and handling
total_null=df.isnull().sum()
print("Null values ".center(20,"_"))
print(total_null)

# Null value percentage
percentage=(total_null/len(df))*100
print(percentage)

#1.remove the row with a null values

clean_df=df.dropna()
print(clean_df.isnull().sum())
print("All null values row are removed...!")
clean_df.shape

#2.simple imputation
#replace the null value with mean,median,mode


#Null values are replace by mean
df_mean=df.fillna(df.mean())

#Null values are replaced by median
df_median=df.fillna(df.median())

#Null values are replaced by mode
df_mode=df.fillna(df.median())

#null values replaced dataset
print("After replace")
print(df_mean.head())

#null values removed dataset
print("\nAfter remove")
print(clean_df.head())

